/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/_workspace.analytics'
import { Route as WorkspaceCompaniesRouteImport } from './routes/_workspace.companies'
import { Route as WorkspaceDailyEntryRouteImport } from './routes/_workspace.daily-entry'
import { Route as WorkspacePipelineRouteImport } from './routes/_workspace.pipeline'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceWeeklyReviewRouteImport } from './routes/_workspace.weekly-review'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCompaniesRoute = WorkspaceCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDailyEntryRoute = WorkspaceDailyEntryRouteImport.update({
  id: '/daily-entry',
  path: '/daily-entry',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePipelineRoute = WorkspacePipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWeeklyReviewRoute = WorkspaceWeeklyReviewRouteImport.update({
  id: '/weekly-review',
  path: '/weekly-review',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/analytics': typeof WorkspaceAnalyticsRoute
  '/companies': typeof WorkspaceCompaniesRoute
  '/daily-entry': typeof WorkspaceDailyEntryRoute
  '/pipeline': typeof WorkspacePipelineRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/weekly-review': typeof WorkspaceWeeklyReviewRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof WorkspaceAnalyticsRoute
  '/companies': typeof WorkspaceCompaniesRoute
  '/daily-entry': typeof WorkspaceDailyEntryRoute
  '/pipeline': typeof WorkspacePipelineRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/weekly-review': typeof WorkspaceWeeklyReviewRoute
  '/': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/_workspace/companies': typeof WorkspaceCompaniesRoute
  '/_workspace/daily-entry': typeof WorkspaceDailyEntryRoute
  '/_workspace/pipeline': typeof WorkspacePipelineRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/weekly-review': typeof WorkspaceWeeklyReviewRoute
  '/_workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/companies'
    | '/daily-entry'
    | '/pipeline'
    | '/settings'
    | '/weekly-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/companies'
    | '/daily-entry'
    | '/pipeline'
    | '/settings'
    | '/weekly-review'
    | '/'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/analytics'
    | '/_workspace/companies'
    | '/_workspace/daily-entry'
    | '/_workspace/pipeline'
    | '/_workspace/settings'
    | '/_workspace/weekly-review'
    | '/_workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/analytics': {
      id: '/_workspace/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/companies': {
      id: '/_workspace/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof WorkspaceCompaniesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/daily-entry': {
      id: '/_workspace/daily-entry'
      path: '/daily-entry'
      fullPath: '/daily-entry'
      preLoaderRoute: typeof WorkspaceDailyEntryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/pipeline': {
      id: '/_workspace/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof WorkspacePipelineRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/weekly-review': {
      id: '/_workspace/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof WorkspaceWeeklyReviewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceCompaniesRoute: typeof WorkspaceCompaniesRoute
  WorkspaceDailyEntryRoute: typeof WorkspaceDailyEntryRoute
  WorkspacePipelineRoute: typeof WorkspacePipelineRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceWeeklyReviewRoute: typeof WorkspaceWeeklyReviewRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceCompaniesRoute: WorkspaceCompaniesRoute,
  WorkspaceDailyEntryRoute: WorkspaceDailyEntryRoute,
  WorkspacePipelineRoute: WorkspacePipelineRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceWeeklyReviewRoute: WorkspaceWeeklyReviewRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
